// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxwYjJ7Su0BJaIHxYulsjOvfWJR5lvIQ',
    appId: '1:930059102480:web:f1b9636b47e7dc83eb9d95',
    messagingSenderId: '930059102480',
    projectId: 'alanlice',
    authDomain: 'alanlice.firebaseapp.com',
    storageBucket: 'alanlice.appspot.com',
    measurementId: 'G-2BFLSQLJ5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYt_KAjgNhPCym2NFyHPvH2najTabzlc',
    appId: '1:930059102480:android:3d2019f1296a2392eb9d95',
    messagingSenderId: '930059102480',
    projectId: 'alanlice',
    storageBucket: 'alanlice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAekXGZLIwpepTWy7j6rE19Nrw4vTcXYXc',
    appId: '1:930059102480:ios:83226e639820bd29eb9d95',
    messagingSenderId: '930059102480',
    projectId: 'alanlice',
    storageBucket: 'alanlice.appspot.com',
    androidClientId: '930059102480-7g6k1bv8fdl9p52s861v72grvosbmfnu.apps.googleusercontent.com',
    iosClientId: '930059102480-tnapuf13sbk5qkkqrlpqsqipjo53kj1k.apps.googleusercontent.com',
    iosBundleId: 'com.alanlice.alanliceV2',
  );
}
